SalesforceCICD/force-app/main/default/objects/Bicycle__c/Bicycle__c.object-meta.xml
<CustomObject>
    <label>Bicycle</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Bicycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bicycles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceCICD/force-app/main/default/objects/Bicycle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bicycles</relationshipLabel>
    <relationshipName>Bicycles</relationshipName>
    <type>Lookup</type>
</CustomField>

SalesforceCICD/force-app/main/default/objects/Bicycle__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pinarello</fullName>
            </value>
            <value>
                <fullName>Simplon</fullName>
            </value>
            <value>
                <fullName>Canyon</fullName>
            </value>
            <value>
                <fullName>Kuota</fullName>
            </value>
            <value>
                <fullName>Scott</fullName>
            </value>
            <value>
                <fullName>Cube</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceCICD/force-app/main/default/objects/Bicycle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fasto-001</fullName>
            </value>
            <value>
                <fullName>Fasto-002</fullName>
            </value>
            <value>
                <fullName>Fasto-003</fullName>
            </value>
            <value>
                <fullName>Kiaro100</fullName>
            </value>
            <value>
                <fullName>Kiaro200</fullName>
            </value>
            <value>
                <fullName>Kiaro200A</fullName>
            </value>
            <value>
                <fullName>Neuron CF9</fullName>
            </value>
            <value>
                <fullName>Neuron CF10</fullName>
            </value>
            <value>
                <fullName>Neuron CF20</fullName>
            </value>
            <value>
                <fullName>Kross1</fullName>
            </value>
            <value>
                <fullName>Kross2</fullName>
            </value>
            <value>
                <fullName>Kross3A</fullName>
            </value>
            <value>
                <fullName>Kross3B</fullName>
            </value>
            <value>
                <fullName>Beast-1000</fullName>
            </value>
            <value>
                <fullName>Beast-2000</fullName>
            </value>
            <value>
                <fullName>Moun-001</fullName>
            </value>
            <value>
                <fullName>Moun-002</fullName>
            </value>
            <value>
                <fullName>Moun-003</fullName>
            </value>
            <value>
                <fullName>Gradle-001</fullName>
            </value>
            <value>
                <fullName>Gradle-002</fullName>
            </value>
            <value>
                <fullName>Gradle-003</fullName>
            </value>
            <value>
                <fullName>Gradle-004</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceCICD/force-app/main/default/objects/Bicycle__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SalesforceCICD/force-app/main/default/classes/BicycleRevenueListController.cls
/*
Apex Class  Bicycle Revenue List Controller for LWC
*/
   
public with sharing class BicycleRevenueListController {
        
        @AuraEnabled(cacheable=true)
        public static List<BicycleRevenueWrapper> getRevenueList(Id accountid)
        {
         
            Map<String,BicycleRevenueWrapper> brWrapperMap= new Map<String,BicycleRevenueWrapper>();
             
            try
            {
                for(Bicycle__c brecord:[select id,Registration_Date__c,convertCurrency(Revenue__c), Brand__c, Model__c from Bicycle__c  where account__c=:accountid WITH USER_MODE order by Registration_Date__c  ])
                {
                    if(!brWrapperMap.containsKey(brecord.Brand__c+brecord.Model__c))
                    {   
                        brWrapperMap.put(brecord.Brand__c+brecord.Model__c,new BicycleRevenueWrapper(brecord.Brand__c+brecord.Model__c,brecord.Brand__c,brecord.Model__c,brecord.Registration_Date__c,brecord.Revenue__c));
                    }
                    else
                    {
                      BicycleRevenueWrapper brwrapper=brWrapperMap.get(brecord.Brand__c+brecord.Model__c);
                      brwrapper.total_revenue+=brecord.Revenue__c;
                      brWrapperMap.put(brecord.Brand__c+brecord.Model__c,brwrapper);                  
                    }                   
                }   
                
                return brWrapperMap.values();
            }
            catch(Exception e)
            {
               throw new AuraHandledException('Something Went wrong ,Please Contact the Administrator :'+e.getMessage());             
            }
           
        }
    }